from app.core.config import settings
from app.core.constants import (
    BASE58_ALPHABET,
    DEFAULT_SHORT_CODE_LENGTH,
    MAX_CUSTOM_ALIAS_LENGTH,
    REGEX_SHORT_CODE_PATTERN,
)
from app.core.exceptions import (
    URLShortenerException,
    InvalidURLException,
    ShortCodeNotFoundException,
    CustomAliasTakenException,
    URLExpiredException,
    InvalidShortCodeFormatException,
    AnonymousAliasNotAllowedException,
    CustomAliasLimitExceededException,
    UserAlreadyExistsException,
    InvalidCredentialsException,
    InvalidTokenException,
    ApiKeyNotFoundException,
    InvalidApiKeyException,
    ApiKeyLimitExceededException,
    QuotaExceededException,
)
from app.core.utils import (
    encode_base58,
    decode_base58,
    validate_url,
    validate_short_code_format,
    generate_unique_short_code_from_id,
)
from app.core.security import (
    hash_password,
    verify_password,
    create_access_token,
    decode_access_token,
    create_refresh_token,
    generate_api_key,
    hash_api_key,
)
from app.core.geoip import lookup_country, close_reader, get_reader

__all__ = [
    "settings",
    "BASE58_ALPHABET",
    "DEFAULT_SHORT_CODE_LENGTH",
    "MAX_CUSTOM_ALIAS_LENGTH",
    "REGEX_SHORT_CODE_PATTERN",
    "URLShortenerException",
    "InvalidURLException",
    "ShortCodeNotFoundException",
    "CustomAliasTakenException",
    "URLExpiredException",
    "InvalidShortCodeFormatException",
    "AnonymousAliasNotAllowedException",
    "CustomAliasLimitExceededException",
    "UserAlreadyExistsException",
    "InvalidCredentialsException",
    "InvalidTokenException",
    "ApiKeyNotFoundException",
    "InvalidApiKeyException",
    "ApiKeyLimitExceededException",
    "QuotaExceededException",
    "encode_base58",
    "decode_base58",
    "validate_url",
    "validate_short_code_format",
    "generate_unique_short_code_from_id",
    "hash_password",
    "verify_password",
    "create_access_token",
    "decode_access_token",
    "create_refresh_token",
    "generate_api_key",
    "hash_api_key",
    "lookup_country",
    "close_reader",
    "get_reader",
]
